### PR TITLE
Added Travis CI

### PR DESCRIPTION
**Pull request by richelbilderbeek**
Hi @thliebig,

I have added Travis CI (a continuous integration service) that checks if the code can still be built after a `git push`. It assures quality of the GitHub.

If, and only if, you accept this Pull Request, will I use this GitHub in [my Travis CI tutorial](https://github.com/richelbilderbeek/travis_cpp_tutorial). Else I'll have to use my Fork, but I'd strongly prefer to use yours.

If you accept, I am sorry to say, you'll need to do the following things
 * Create a Travis CI ([travis-ci.org](travis-ci.org)) account for `thliebig`. This will be easy: you can sign in with your GitHub account
 * Activate this repo in Travis
 * Replace `richelbilderbeek` in the README.md by `thliebig`

If you are unaware of Travis CI:

 * [My Travis CI tutorial](https://github.com/richelbilderbeek/travis_cpp_tutorial)
 * [My 'Simplify C++' blog post about Travis CI](https://arne-mertz.de/2017/04/continuous-integration-travis-ci/)
 * [A CppCast interview with me about Travis CI](http://cppcast.com/2017/06/richel-bilderbeek/)

### CODE REVIEW

**Comment by thliebig** [comment]
Hi,
the idea of using a service like this makes a lot of sense. But just not so much for a repo like this?
I do not make any changes to this library as it is just an upstream copy and not my work.
I only added a  few build instructions and so on. But I have not done any changes for many years and I do not plan to make any in the near future.
Thus I'm pretty sure it builds alright at the moment and since I'm not going to change anything, that should not change, right?

**Comment by richelbilderbeek** [comment]
<rest assured: it builds just fine :-)

**Comment by richelbilderbeek** [comment]
Note: I've added a TARGET as well, as it caused [a project of my](https://github.com/richelbilderbeek/travis_qmake_gcc_cpp98_fparser) not to work.

**Comment by richelbilderbeek** [comment]
@thliebig: what do you think about this Pull Request?

**Comment by thliebig** [comment]
As I have said earlier, I do not make any kind of changes to fparser, thus I do not see any good reason for CI...

**Comment by richelbilderbeek** [comment]
OK.

**Pull request closed without merging**
